### ISSUE TITLE
Python 3 regressions in knossosdataset

### ISSUE THREAD

**Issue by mdraw** [knossos-project/knossos_utils#17]
The last few commits require some changes to work on Python 3.
From a quick glance:
- urllib2 and StringIO have to be replaced
- ~~numpy string reading functions (fromstring, fromfile) need to be tested with real data. They probably won't work with byte strings.~~

**Comment by sdorkenw** [comment]
Right
- urllib2 --> urllib
- from StringIO import StringIO --> from io import StringIO
- numpy string reading function were tested with real data, but not under Py3. However, they were already used before the recent commits.

**Comment by mdraw** [comment]
Ah, I see, I was confused about the string reading part. The earlier problems with np.fromstring were due to joining bytes and strings (https://github.com/knossos-project/knossos_utils/commit/358339bb4881a8d0c7d1dafd411cee7338d248d4), but this doesn't apply here.

**Comment by sdorkenw** [comment]
Implemented:
- urllib2 --> requests
- StringIO.StringIO --> io.BytesIO
