### ISSUE TITLE
Can Python 2.7use knossos_ utils？

### ISSUE THREAD

**Issue by liuyx599** [knossos-project/knossos_utils#29]
I saw the README descrbing knossos_utils is A **Python 3.x l**ibrary for interacting with KNOSSOS datasets and annotation files.

**Comment by my-tien** [comment]
No, knossos_utils is not compatible with Python2.7. We use some Syntax that is only available in Python 3, e.g. the print built-in function and type annotations.

**Comment by Optiligence** [comment]
@liuyx599 what keeps you with python 2 at this point?
