### ISSUE TITLE
Parsing of edges between different things is not yet supported

### ISSUE THREAD

**Issue by hash-ir** [knossos-project/knossos_utils#34]
Hi,

I get a warning when I load an annotated skeleton using knossos-utils. `Warning: Parsing of edges between different things is not yet supported, skipping edge: 56451 -> 18342` and this warning is presented for many edges. This comes from [here](https://github.com/knossos-project/knossos_utils/blob/d06c2bcd42e75435e16b4ba8f285fa4b20a66b84/knossos_utils/skeleton.py#L832). 

I don't quite understand what this would mean. I use the annotated skeleton to assign labels to the vertices of the mesh (using a kd-tree search). Is it safe to ignore this warning? I use `knossos-utils==0.1`

**Comment by Optiligence** [comment]
If you have nodes in several trees in KNOSSOS and nodes from different trees are connected, `knossos_utils` doesn’t seem to be able to properly work with those edges.

**Comment by hash-ir** [comment]
That explains it, thank you. Is there also a way in Knossos to combine those trees?

**Comment by Optiligence** [comment]
You can merge trees via the context menu on trees in the skeleton table with the tracing advanced mode active.
